apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - ../../base
  - externalsecrets.yaml
  - hpa.yaml
  - ingress.yaml
  - servicemonitor.yaml

patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: auth-service

images:
  - name: REPOSITORY/auth-microservice
    newName: kristianrpo30/auth-microservice
    newTag: latest